apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: m-svc-2
build:
  artifacts:
  - image: m-svc-2-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./k8s/deployment.yaml
  # helm:
  #   releases:
  #   - name: m-svc-2
  #     remoteChart: sonal-github-helm-repo/micro-svc-helm-chart
  #     valuesFiles:
  #     - '../skaffold-k8s-state/helm-values/m-svc-2/local/values.yaml'
  #     artifactOverrides:
  #       image: m-svc-2-image
  #     imageStrategy:
  #       helm: {}  
