apiVersion: v1
kind: Service
metadata:
  name: m-svc-2
  labels:
    app: m-svc-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: m-svc-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-svc-2
  labels:
    app: m-svc-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-svc-2
  template:
    metadata:
      labels:
        app: m-svc-2
    spec:
      containers:
      - name: m-svc-2-image
        image: m-svc-2-image
        imagePullPolicy: IfNotPresent
        env:
        - name: "spring.config.location"
          value: "/config/"
        - name: "spring.profiles.active"
          value: "local"  
        volumeMounts:
        - name: config-vol
          mountPath: "/config"
          readOnly: true
      
      volumes:
      - name: config-vol
        configMap:
          name: m-svc-1-cm
          items:
          - key: "application.properties"
            path: "application.properties"
          - key: "application-local.properties"
            path: "application-local.properties"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  m-svc-1-cm
data:
  # spring application configs
  application.properties: |
    
    spring.application.name=m-svc-2
    server.port=8080
    management.endpoints.web.exposure.include=*
    management.info.git.mode=full
    spring.webflux.base-path=/m-svc-2
    com.sonal.skaffold.demo.msvc1.greetings.message=Hello
  
  application-local.properties: |
    server.port=8080
    com.sonal.skaffold.demo.msvc1.greetings.message=Local Hello
 