apiVersion: v1
kind: Service
metadata:
  name: m-svc2
  labels:
    app: m-svc2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: m-svc2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-svc2
  labels:
    app: m-svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-svc2
  template:
    metadata:
      labels:
        app: m-svc2
    spec:
      containers:
      - name: m-svc2-image
        image: m-svc2-image
        imagePullPolicy: IfNotPresent
