apiVersion: v1
kind: ConfigMap
metadata:
  name:  m-svc-2-cm
data:
  # spring application configs
  application.properties: |
    
    spring.application.name=m-svc-2
    server.port=8080
    management.endpoints.web.exposure.include=*
    management.info.git.mode=full
    spring.webflux.base-path=/m-svc-2
    com.sonal.skaffold.demo.msvc1.greetings.message=Hello
  
  application-local.properties: |
    server.port=8080
    com.sonal.skaffold.demo.msvc1.greetings.message=Local Hello