apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
        - name: {{ .Values.applicationName }}
          image: {{ .Values.container.image }} 
          imagePullPolicy: {{ .Values.container.imagePullPolicy }} 
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          env:
          - name: "spring.config.location"
            value: "/config/"
          - name: "spring.profiles.active"
            value: "local"  
          volumeMounts:
          - name: config-vol
            mountPath: "/config"
            readOnly: true    
      volumes:
        - name: config-vol
          configMap:
            name: m-svc-2-cm
            items:
            - key: "application.properties"
              path: "application.properties"
            - key: "application-local.properties"
              path: "application-local.properties"    
